### ISSUE TITLE
Health-lifesci.schema.org Extension master plan and backlog

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#38]
This is an internal place for Health-lifesci.schema.org Extension master plan and backlog.
We will assembly here all agreed on items, to be implemented in future. The purpose is not to lose track of item scattered in several issues comments.
All listed items should be linked to an opened issue at https://github.com/schemaorg/schemaorg/issues.
## Release plans
- [x] Health-lifesci.schema.org Extension v.1 published along the Schema.org 3.0
- [ ] Health-lifesci.schema.org Extension v.2 ready to be published: waiting the community interest to pick up the vocabulary
- [ ] Health-lifesci.schema.org Extension v.3 ready to be published: waiting the community interest to pick up the vocabulary
## Issues backlog and planning
- [ ] https://github.com/schemaorg/schemaorg/issues/1114   ==> [target: waiting for community interest]
- [ ] https://github.com/schemaorg/schemaorg/issues/296#issuecomment-71867741  ==>  [target: waiting for community interest]
- [ ] https://github.com/schemaorg/schemaorg/issues/492#issuecomment-213704477  ==> [target: waiting for community interest]
- [ ] https://github.com/schemaorg/schemaorg/issues/492#issuecomment-228062967  ==> [target: waiting for community interest]
- [ ] https://github.com/schemaorg/schemaorg/issues/492#issuecomment-213611103  ==> [target: waiting for community interest]
- [ ] https://github.com/schemaorg/schemaorg/issues/492#issuecomment-233254224  ==> [target: waiting for community interest]
